const admin = require('./apiAdminController');
exports.list = admin.aircraftList;
exports.newForm = admin.aircraftNew;
exports.editForm = admin.aircraftEdit;
exports.newSeatForm = admin.seatNew;
exports.detail = admin.aircraftDetail;
exports.create = admin.aircraftCreate;
exports.update = admin.aircraftUpdate;
exports.remove = admin.aircraftRemove;
